[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
asymmetric_spl = "76vuoVBk8VtxGHd2BVeTFq3n3aSAFtqzKUncrgrczSNK"
workspace = "BhHNeG8Ck5bxm9sMYdgXpw769oPsQLyQY21rWewvNn3r"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
